< script type = "text/x-config" > {
    "subbuzz": {
        "description": "",
        "form": "quiz",
        "header": "",
        "id": "122423124",
        "numbered_questions": 0,
        "questions": [{
            "answers": [{
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521190",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-03/enhanced-12078-1552067601-1.png",
                "image_height": "370",
                "image_text": "Cereal",
                "image_width": "520",
                "personality_index": 2,
                "row_start": true,
                "row_end": false,
                "is_last": false,
                "answer_count": 1
            },
            {
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521191",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-05/enhanced-28556-1552067594-1.png",
                "image_height": "370",
                "image_text": "Pop Tarts",
                "image_width": "520",
                "personality_index": 1,
                "row_start": false,
                "row_end": true,
                "is_last": false,
                "answer_count": 2
            },
            {
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521192",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-01/enhanced-2655-1552067600-1.png",
                "image_height": "370",
                "image_text": "Pancakes",
                "image_width": "520",
                "personality_index": 3,
                "row_start": true,
                "row_end": false,
                "is_last": false,
                "answer_count": 3
            },
            {
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521193",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-04/enhanced-25395-1552067600-1.png",
                "image_height": "370",
                "image_text": "Bacon and eggs",
                "image_width": "520",
                "personality_index": 0,
                "row_start": false,
                "row_end": true,
                "is_last": true,
                "answer_count": 4
            }],
            "attribution": "",
            "description": null,
            "display_answer_titles": 0,
            "display_poll_question": 1,
            "display_result_image": 1,
            "format": "2-UP",
            "header": "",
            "id": "365521189",
            "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-06/original-11389-1552067597-3.png",
            "image_height": "359",
            "image_text": "What do you usually eat for breakfast?",
            "image_width": "1024",
            "data_src": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-06/original-11389-1552067597-3.png",
            "data_gif_src": null,
            "is_input": false,
            "is_text_type": false,
            "count": 1,
            "question_type": "image",
            "title_number": "1.",
            "unreveal_class": "",
            "fake_answers": [],
            "is_legasy_quiz": 0,
            "question_id": "365521189",
            "legacy_class": "subbuzz-quiz__quiestion--quiz-v2",
            "has_reveal": false,
            "alt_text": "",
            "format_grid": 2,
            "temp_answer_image": "data:image/gif;base64,R0lGODlhAwACAPAAAAAAAAAAACH5BAEAAAAALAAAAAADAAIAAAIChF8AOw==",
            "question_type_class": "subbuzz-quiz__question--image"
        },
        {
            "answers": [{
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521195",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-06/enhanced-11459-1552067595-1.png",
                "image_height": "370",
                "image_text": "Cheese and crackers",
                "image_width": "520",
                "personality_index": 1,
                "row_start": true,
                "row_end": false,
                "is_last": false,
                "answer_count": 1
            },
            {
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521196",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-02/enhanced-20894-1552067600-1.png",
                "image_height": "370",
                "image_text": "Oreos",
                "image_width": "520",
                "personality_index": 0,
                "row_start": false,
                "row_end": true,
                "is_last": false,
                "answer_count": 2
            },
            {
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521197",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-04/enhanced-25386-1552067595-1.png",
                "image_height": "370",
                "image_text": "Greek yogurt",
                "image_width": "520",
                "personality_index": 2,
                "row_start": true,
                "row_end": false,
                "is_last": false,
                "answer_count": 3
            },
            {
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521198",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-05/enhanced-28686-1552067603-2.png",
                "image_height": "370",
                "image_text": "Almonds",
                "image_width": "520",
                "personality_index": 3,
                "row_start": false,
                "row_end": true,
                "is_last": true,
                "answer_count": 4
            }],
            "attribution": "",
            "description": null,
            "display_answer_titles": 0,
            "display_poll_question": 1,
            "display_result_image": 1,
            "format": "2-UP",
            "header": "",
            "id": "365521194",
            "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-06/original-11429-1552067600-3.png",
            "image_height": "359",
            "image_text": "What do you want for a snack?",
            "image_width": "1024",
            "data_src": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-06/original-11429-1552067600-3.png",
            "data_gif_src": null,
            "is_input": false,
            "is_text_type": false,
            "count": 2,
            "question_type": "image",
            "title_number": "2.",
            "unreveal_class": "",
            "fake_answers": [],
            "is_legasy_quiz": 0,
            "question_id": "365521194",
            "legacy_class": "subbuzz-quiz__quiestion--quiz-v2",
            "has_reveal": false,
            "alt_text": "",
            "format_grid": 2,
            "temp_answer_image": "data:image/gif;base64,R0lGODlhAwACAPAAAAAAAAAAACH5BAEAAAAALAAAAAADAAIAAAIChF8AOw==",
            "question_type_class": "subbuzz-quiz__question--image"
        },
        {
            "answers": [{
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521200",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-01/enhanced-2610-1552067601-1.png",
                "image_height": "370",
                "image_text": "Grilled cheese",
                "image_width": "520",
                "personality_index": 3,
                "row_start": true,
                "row_end": false,
                "is_last": false,
                "answer_count": 1
            },
            {
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521201",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-03/enhanced-12002-1552067595-1.png",
                "image_height": "370",
                "image_text": "Burrito",
                "image_width": "520",
                "personality_index": 1,
                "row_start": false,
                "row_end": true,
                "is_last": false,
                "answer_count": 2
            },
            {
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521202",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-02/enhanced-20854-1552067601-1.png",
                "image_height": "370",
                "image_text": "Hamburger and fries",
                "image_width": "520",
                "personality_index": 0,
                "row_start": true,
                "row_end": false,
                "is_last": false,
                "answer_count": 3
            },
            {
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521203",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-04/enhanced-25326-1552067595-6.png",
                "image_height": "370",
                "image_text": "Salad",
                "image_width": "520",
                "personality_index": 2,
                "row_start": false,
                "row_end": true,
                "is_last": true,
                "answer_count": 4
            }],
            "attribution": "",
            "description": null,
            "display_answer_titles": 0,
            "display_poll_question": 1,
            "display_result_image": 1,
            "format": "2-UP",
            "header": "",
            "id": "365521199",
            "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-04/original-25300-1552067600-3.png",
            "image_height": "359",
            "image_text": "What do you want for lunch?",
            "image_width": "1024",
            "data_src": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-04/original-25300-1552067600-3.png",
            "data_gif_src": null,
            "is_input": false,
            "is_text_type": false,
            "count": 3,
            "question_type": "image",
            "title_number": "3.",
            "unreveal_class": "",
            "fake_answers": [],
            "is_legasy_quiz": 0,
            "question_id": "365521199",
            "legacy_class": "subbuzz-quiz__quiestion--quiz-v2",
            "has_reveal": false,
            "alt_text": "",
            "format_grid": 2,
            "temp_answer_image": "data:image/gif;base64,R0lGODlhAwACAPAAAAAAAAAAACH5BAEAAAAALAAAAAADAAIAAAIChF8AOw==",
            "question_type_class": "subbuzz-quiz__question--image"
        },
        {
            "answers": [{
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521205",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-03/enhanced-11915-1552067596-1.png",
                "image_height": "370",
                "image_text": "Ice cream",
                "image_width": "520",
                "personality_index": 2,
                "row_start": true,
                "row_end": false,
                "is_last": false,
                "answer_count": 1
            },
            {
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521206",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-02/enhanced-20855-1552067601-5.png",
                "image_height": "370",
                "image_text": "Pretzels",
                "image_width": "520",
                "personality_index": 1,
                "row_start": false,
                "row_end": true,
                "is_last": false,
                "answer_count": 2
            },
            {
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521207",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-06/enhanced-11495-1552067596-2.png",
                "image_height": "370",
                "image_text": "Potato chips",
                "image_width": "520",
                "personality_index": 0,
                "row_start": true,
                "row_end": false,
                "is_last": false,
                "answer_count": 3
            },
            {
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521208",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-05/enhanced-28597-1552067597-1.png",
                "image_height": "370",
                "image_text": "Candy bar",
                "image_width": "520",
                "personality_index": 3,
                "row_start": false,
                "row_end": true,
                "is_last": true,
                "answer_count": 4
            }],
            "attribution": "",
            "description": null,
            "display_answer_titles": 0,
            "display_poll_question": 1,
            "display_result_image": 1,
            "format": "2-UP",
            "header": "",
            "id": "365521204",
            "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-03/original-12129-1552067598-3.png",
            "image_height": "359",
            "image_text": "Come on! Pick another snack:",
            "image_width": "1024",
            "data_src": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-03/original-12129-1552067598-3.png",
            "data_gif_src": null,
            "is_input": false,
            "is_text_type": false,
            "count": 4,
            "question_type": "image",
            "title_number": "4.",
            "unreveal_class": "",
            "fake_answers": [],
            "is_legasy_quiz": 0,
            "question_id": "365521204",
            "legacy_class": "subbuzz-quiz__quiestion--quiz-v2",
            "has_reveal": false,
            "alt_text": "",
            "format_grid": 2,
            "temp_answer_image": "data:image/gif;base64,R0lGODlhAwACAPAAAAAAAAAAACH5BAEAAAAALAAAAAADAAIAAAIChF8AOw==",
            "question_type_class": "subbuzz-quiz__question--image"
        },
        {
            "answers": [{
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521210",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-02/enhanced-20838-1552067602-1.png",
                "image_height": "370",
                "image_text": "Fried chicken",
                "image_width": "520",
                "personality_index": 3,
                "row_start": true,
                "row_end": false,
                "is_last": false,
                "answer_count": 1
            },
            {
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521211",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-02/enhanced-20853-1552067597-7.png",
                "image_height": "370",
                "image_text": "Shrimp scampi",
                "image_width": "520",
                "personality_index": 2,
                "row_start": false,
                "row_end": true,
                "is_last": false,
                "answer_count": 2
            },
            {
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521212",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-01/enhanced-2552-1552067602-1.png",
                "image_height": "370",
                "image_text": "Lasagna",
                "image_width": "520",
                "personality_index": 1,
                "row_start": true,
                "row_end": false,
                "is_last": false,
                "answer_count": 3
            },
            {
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521213",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-05/enhanced-28671-1552067597-1.png",
                "image_height": "370",
                "image_text": "Pizza",
                "image_width": "520",
                "personality_index": 0,
                "row_start": false,
                "row_end": true,
                "is_last": true,
                "answer_count": 4
            }],
            "attribution": "",
            "description": null,
            "display_answer_titles": 0,
            "display_poll_question": 1,
            "display_result_image": 1,
            "format": "2-UP",
            "header": "",
            "id": "365521209",
            "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-05/original-28721-1552067603-3.png",
            "image_height": "359",
            "image_text": "What's for dinner?",
            "image_width": "1024",
            "data_src": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-05/original-28721-1552067603-3.png",
            "data_gif_src": null,
            "is_input": false,
            "is_text_type": false,
            "count": 5,
            "question_type": "image",
            "title_number": "5.",
            "unreveal_class": "",
            "fake_answers": [],
            "is_legasy_quiz": 0,
            "question_id": "365521209",
            "legacy_class": "subbuzz-quiz__quiestion--quiz-v2",
            "has_reveal": false,
            "alt_text": "",
            "format_grid": 2,
            "temp_answer_image": "data:image/gif;base64,R0lGODlhAwACAPAAAAAAAAAAACH5BAEAAAAALAAAAAADAAIAAAIChF8AOw==",
            "question_type_class": "subbuzz-quiz__question--image"
        },
        {
            "answers": [{
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521217",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-04/enhanced-25351-1552067602-1.png",
                "image_height": "370",
                "image_text": "Cheesecake",
                "image_width": "520",
                "personality_index": 2,
                "row_start": true,
                "row_end": false,
                "is_last": false,
                "answer_count": 1
            },
            {
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521218",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-05/enhanced-28671-1552067598-5.png",
                "image_height": "370",
                "image_text": "Brownies",
                "image_width": "520",
                "personality_index": 1,
                "row_start": false,
                "row_end": true,
                "is_last": false,
                "answer_count": 2
            },
            {
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521219",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-02/enhanced-20853-1552067598-11.png",
                "image_height": "370",
                "image_text": "Doughnuts",
                "image_width": "520",
                "personality_index": 0,
                "row_start": true,
                "row_end": false,
                "is_last": false,
                "answer_count": 3
            },
            {
                "attribution": "",
                "description": null,
                "format": null,
                "header": "",
                "id": "365521220",
                "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-03/enhanced-12091-1552067599-1.png",
                "image_height": "370",
                "image_text": "Apple pie",
                "image_width": "520",
                "personality_index": 3,
                "row_start": false,
                "row_end": true,
                "is_last": true,
                "answer_count": 4
            }],
            "attribution": "",
            "description": null,
            "display_answer_titles": 0,
            "display_poll_question": 1,
            "display_result_image": 1,
            "format": "2-UP",
            "header": "",
            "id": "365521215",
            "image": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-04/original-25264-1552067599-7.png",
            "image_height": "359",
            "image_text": "Finally, what are you eating for dessert?",
            "image_width": "1024",
            "data_src": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/8/12/enhanced/buzzfeed-prod-web-04/original-25264-1552067599-7.png",
            "data_gif_src": null,
            "is_input": false,
            "is_text_type": false,
            "count": 6,
            "question_type": "image",
            "title_number": "6.",
            "unreveal_class": "",
            "fake_answers": [],
            "is_legasy_quiz": 0,
            "question_id": "365521215",
            "legacy_class": "subbuzz-quiz__quiestion--quiz-v2",
            "has_reveal": false,
            "alt_text": "",
            "format_grid": 2,
            "temp_answer_image": "data:image/gif;base64,R0lGODlhAwACAPAAAAAAAAAAACH5BAEAAAAALAAAAAADAAIAAAIChF8AOw==",
            "question_type_class": "subbuzz-quiz__question--image"
        }],
        "results": [{
            "attribution": "",
            "description": null,
            "display_vote_count": "0",
            "format": null,
            "header": "Milo",
            "hide_results": "0",
            "id": "365521185",
            "image": "",
            "image_height": null,
            "image_width": null,
            "reorder_results": "1",
            "data_src": "",
            "data_gif_src": null,
            "is_trivia": false,
            "is_checklist": false
        },
        {
            "attribution": "",
            "description": null,
            "display_vote_count": "0",
            "format": null,
            "header": "Axel",
            "hide_results": "0",
            "id": "365521186",
            "image": "",
            "image_height": null,
            "image_width": null,
            "reorder_results": "1",
            "data_src": "",
            "data_gif_src": null,
            "is_trivia": false,
            "is_checklist": false
        },
        {
            "attribution": "",
            "description": null,
            "display_vote_count": "0",
            "format": null,
            "header": "Charlotte",
            "hide_results": "0",
            "id": "365521187",
            "image": "",
            "image_height": null,
            "image_width": null,
            "reorder_results": "1",
            "data_src": "",
            "data_gif_src": null,
            "is_trivia": false,
            "is_checklist": false
        },
        {
            "attribution": "",
            "description": null,
            "display_vote_count": "0",
            "format": null,
            "header": "Amelia",
            "hide_results": "0",
            "id": "365521188",
            "image": "",
            "image_height": null,
            "image_width": null,
            "reorder_results": "1",
            "data_src": "",
            "data_gif_src": null,
            "is_trivia": false,
            "is_checklist": false
        }],
        "type": "personality",
        "lock_question_on_answer": 0
    },
    "sharing": {
        "name": "I got <%=&value%>!  <%=&title%>",
        "description": "<%=&description%>",
        "picture": "<%=resultImage%>",
        "title": "I got <%=&value%>! <%=&title%>",
        "text": "I got <%=&value%>!"
    }
} < /script>/</script>